package techgen.spring;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import techgen.core.gm.GenerationModel;
import techgen.core.model.ContractFile;
import techgen.core.model.ManifestJson;
import techgen.core.pipeline.GmBuilder;
import techgen.core.pipeline.Loader;
import techgen.core.report.BuildReport;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * T4.4 — Boundary externals + client seam + boundary validation + Uncharted (SPEC M4; referans
 * {@code docs/referans/gen-dotnet-emisyon-sozlesmesi.md} §1 Boundary (`:913-955`/`:959-974`/
 * `:977-1014`) + Uncharted (`:1017-1071`) + §7). Fixture canlı örnekler: {@code PaymentGateway}
 * external (charge/refund, charge validation'lı, callEdge CreateInvoice→PaymentGateway.charge,
 * kind=external) + {@code LegacyLedger} uncharted (post, callEdge WriteAuditLog→LegacyLedger.post,
 * kind=uncharted, entity {@code LedgerEntry}).
 *
 * <p>external ve uncharted disposition farkı (task §2 Why): external kendi entity'sini SAHİPLENMEZ
 * (yalnız çağıran arayüz + human-seam client); uncharted SAHİPLENİR (OWNED POJO, gen-owned stub —
 * human seam DEĞİL). Bu fark iki negatif assert'le kanıtlanır:
 * {@link #unchartedStubClient_isNotHumanSeam_noFileUnderSrc(Path)} ve
 * {@link #unchartedEntity_isPlainPojo_notJpaEntity(Path)}.</p>
 */
class BoundaryEmitTest {

    private static Path fixture(String name) {
        Path fromModuleDir = Path.of("../fixtures", name);
        if (Files.exists(fromModuleDir)) {
            return fromModuleDir;
        }
        return Path.of("fixtures", name);
    }

    private static GenerationModel fixtureGm() {
        Path manifestPath = fixture("manifest.json");
        ManifestJson manifest = Loader.loadManifest(manifestPath);
        ContractFile contract = Loader.loadContract(manifestPath, manifest.contract());
        return GmBuilder.build(manifest, contract);
    }

    private static GenConfig h2Config() {
        return new GenConfig("h2", "inmemory");
    }

    private static String read(Path outDir, String relPath) throws IOException {
        return Files.readString(outDir.resolve(relPath), StandardCharsets.UTF_8);
    }

    private static final String BOUNDARY_IFACE = "gen/java/app/boundary/PaymentGateway.java";
    private static final String BOUNDARY_CLIENT_SEAM = "src/main/java/app/boundary/PaymentGatewayClient.java";
    private static final String BOUNDARY_VALIDATION = "gen/java/app/boundary/PaymentGatewayChargeValidation.java";
    private static final String HANDLER_BASE = "gen/java/app/billing/createinvoice/CreateInvoiceHandlerBase.java";
    private static final String UNCHARTED_FILE = "gen/java/app/uncharted/LegacyLedger.java";
    private static final String UNCHARTED_ENTITY = "gen/java/app/uncharted/LegacyLedgerLedgerEntry.java";

    // ── Step 5.1 — Boundary interface (gen-owned, WriteAlways) ──────────────────────────────────

    @Test
    void paymentGatewayInterface_isEmitted_withMethodsAndServingComment(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, BOUNDARY_IFACE);
        assertTrue(content.startsWith("// <auto-generated/>"), "gen-owned WriteAlways GEN_HEADER almalı");
        assertTrue(content.contains("package app.boundary;"));
        assertTrue(content.contains("import java.math.BigDecimal;"));
        assertTrue(content.contains("public interface PaymentGateway {"));
        assertTrue(content.contains("String charge(BigDecimal amount);"), "charge imzası eksik");
        assertTrue(content.contains("boolean refund(String chargeId);"), "refund imzası eksik");
        assertTrue(content.contains("// serving: @rest() — transport client sorumluluğu"),
                "serving metadata yorumu eksik (§6.2 boundary marker)");
    }

    // ── Step 5.2 — human client seam (writeIfAbsent, marker) + Bootstrap kaydı ──────────────────

    @Test
    void paymentGatewayClientSeam_isEmitted_withVerbatimMarker(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, BOUNDARY_CLIENT_SEAM);
        assertFalse(content.startsWith("// <auto-generated/>"), "human seam GEN_HEADER ALMAMALI");
        assertTrue(content.contains("package app.boundary;"));
        assertTrue(content.contains("public class PaymentGatewayClient implements PaymentGateway {"));
        assertTrue(content.contains(
                "throw new UnsupportedOperationException(\"PaymentGateway.charge: doldurulacak\");"),
                "boundary marker birebir olmalı");
        assertTrue(content.contains(
                "throw new UnsupportedOperationException(\"PaymentGateway.refund: doldurulacak\");"));
    }

    @Test
    void paymentGatewayClientSeam_secondEmit_doesNotOverwrite(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        Path seamFile = outDir.resolve(BOUNDARY_CLIENT_SEAM);
        String custom = "package app.boundary;\n\n"
                + "public class PaymentGatewayClient implements PaymentGateway {\n"
                + "    public String charge(java.math.BigDecimal amount) { return \"ok\"; }\n"
                + "    public boolean refund(String chargeId) { return true; }\n"
                + "}\n";
        Files.writeString(seamFile, custom, StandardCharsets.UTF_8);

        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        assertEquals(custom, read(outDir, BOUNDARY_CLIENT_SEAM),
                "human seam ikinci emit'te EZİLMEMELİ (writeIfAbsent)");
    }

    @Test
    void generatedBootstrap_hasExplicitPaymentGatewayClientBean_noComponentScan(@TempDir Path outDir)
            throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, "gen/java/app/GeneratedBootstrap.java");
        assertTrue(content.contains("import app.boundary.PaymentGateway;"));
        assertTrue(content.contains("import app.boundary.PaymentGatewayClient;"));
        assertTrue(content.contains("public PaymentGateway paymentGatewayClient() {"));
        assertTrue(content.contains("return new PaymentGatewayClient();"));
        assertTrue(content.contains("@Configuration"));
        assertFalse(content.contains("@ComponentScan"), "component-scan YASAK (SPEC §12/4 tam-açık kayıt)");
    }

    // ── Step 5.3 — caller-side boundary validation (INV-4) ───────────────────────────────────────

    @Test
    void paymentGatewayChargeValidation_isEmitted_withCompareToForm(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, BOUNDARY_VALIDATION);
        assertTrue(content.startsWith("// <auto-generated/>"));
        assertTrue(content.contains("package app.boundary;"));
        assertTrue(content.contains("public final class PaymentGatewayChargeValidation {"));
        assertTrue(content.contains(
                "return (input.amount().compareTo(new BigDecimal(\"0\")) > 0);"),
                "boundary validation compareTo formu birebir olmalı");
        assertTrue(content.contains("public static boolean validation0("));
    }

    // ── Step 5.2 — Ctor-senkron: callEdges.from ile HandlerBase boundary alanı ──────────────────

    @Test
    void createInvoiceHandlerBase_hasPaymentGatewayField_fromCallEdge(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, HANDLER_BASE);
        assertTrue(content.contains("import app.boundary.PaymentGateway;"));
        assertTrue(content.contains("protected final PaymentGateway paymentGateway;"));
        // T4.4 — boundary EN SONA (M4 ctor-threading kuralı: repos -> idempotent -> events -> boundary).
        assertTrue(content.contains(
                "IdempotencyStore idempotencyStore, EventBus eventBus, PaymentGateway paymentGateway) {"));

        String humanHandler = read(outDir, "src/main/java/app/billing/createinvoice/CreateInvoiceHandler.java");
        assertTrue(humanHandler.contains("import app.boundary.PaymentGateway;"));
        assertTrue(humanHandler.contains(
                "super(invoiceRepository, idempotencyStore, eventBus, paymentGateway);"));

        String wiring = read(outDir, "gen/java/app/billing/BillingWiring.java");
        assertTrue(wiring.contains("import app.boundary.PaymentGateway;"));
        assertTrue(wiring.contains(
                "return new CreateInvoiceHandler(invoiceRepository, idempotencyStore, eventBus, "
                        + "paymentGateway);"));
    }

    @Test
    void writeAuditLogHandlerBase_hasNoBoundaryField_unchartedIsNotWiredIntoCtor(@TempDir Path outDir)
            throws IOException {
        // WriteAuditLog→LegacyLedger callEdge kind=uncharted (external DEĞİL) — Step 5.2 yalnız
        // external callEdges'i ctor'a bağlar; uncharted çağrı-adaptörü ctor-threading DIŞI (task §7 out
        // of scope: callEdges census kaydı T4.5; bu görevde yalnız external wiring'i kapsar).
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, "gen/java/app/ops/writeauditlog/WriteAuditLogHandlerBase.java");
        assertFalse(content.contains("LegacyLedger"), "WriteAuditLog ctor'una uncharted client bağlanmamalı");
    }

    // ── Step 5.4 — Uncharted: gen-owned stub (human seam DEĞİL) + OWNED entity POJO ─────────────

    @Test
    void legacyLedgerFile_isEmitted_withStubInterfaceAndClient(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, UNCHARTED_FILE);
        assertTrue(content.startsWith("// <auto-generated/>"), "uncharted stub gen-owned WriteAlways olmalı");
        assertTrue(content.contains("package app.uncharted;"));
        assertTrue(content.contains("public interface LegacyLedger {"));
        assertTrue(content.contains("boolean post(BigDecimal amount);"));
        assertTrue(content.contains("final class LegacyLedgerStubClient implements LegacyLedger {"));
        assertFalse(content.contains("doldurulacak"),
                "uncharted stub gen-owned (WriteAlways) — 'doldurulacak' human-seam marker'ı TAŞIMAMALI");
    }

    @Test
    void unchartedStubClient_isNotHumanSeam_noFileUnderSrc(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        // negatif assert: external'in aksine, uncharted stub'ı için src/ altında HİÇBİR seam dosyası
        // yazılmaz (gen-owned, human seam DEĞİL — .NET paritesi; anti-pattern §8).
        assertFalse(Files.exists(outDir.resolve("src/main/java/app/uncharted/LegacyLedgerStubClient.java")));
        assertFalse(Files.exists(outDir.resolve("src/main/java/app/uncharted/LegacyLedgerClient.java")));
        assertFalse(Files.isDirectory(outDir.resolve("src/main/java/app/uncharted")),
                "uncharted için src/ dizini hiç oluşmamalı");
    }

    @Test
    void legacyLedgerEntity_isEmitted_asPlainPojo(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, UNCHARTED_ENTITY);
        assertTrue(content.contains("package app.uncharted;"));
        assertTrue(content.contains("public class LegacyLedgerLedgerEntry {"));
        assertTrue(content.contains("private String id;"));
    }

    @Test
    void unchartedEntity_isPlainPojo_notJpaEntity(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, UNCHARTED_ENTITY);
        // negatif assert: uncharted OWNED entity JPA'ya BAĞLANMAZ (anti-pattern §8).
        assertFalse(content.contains("@Entity"), "uncharted owned POJO @Entity TAŞIMAMALI");
        assertFalse(content.contains("jakarta.persistence"), "uncharted owned POJO JPA import'u İÇERMEMELİ");
    }

    // ── build-report realized kayıtları (§7 disposition tablosu) ─────────────────────────────────

    @Test
    void buildReport_realizesBoundaryAndUnchartedConstructs(@TempDir Path outDir) throws IOException {
        BuildReport report = new BuildReport();
        SpringEmitter.emit(fixtureGm(), outDir, report, h2Config());

        assertTrue(report.entries().stream().anyMatch(e -> e.construct().equals("external")
                && e.id().equals("PaymentGateway") && e.status() == BuildReport.ConstructStatus.REALIZED));
        assertTrue(report.entries().stream().anyMatch(e -> e.construct().equals("boundary-op")
                && e.id().equals("PaymentGateway.charge") && e.status() == BuildReport.ConstructStatus.REALIZED));
        assertTrue(report.entries().stream().anyMatch(e -> e.construct().equals("validation")
                && e.id().equals("PaymentGateway.charge") && e.status() == BuildReport.ConstructStatus.REALIZED));
        assertTrue(report.entries().stream().anyMatch(e -> e.construct().equals("serving")
                && e.id().equals("PaymentGateway.charge:rest")
                && e.status() == BuildReport.ConstructStatus.REALIZED));
        assertTrue(report.entries().stream().anyMatch(e -> e.construct().equals("uncharted")
                && e.id().equals("LegacyLedger") && e.status() == BuildReport.ConstructStatus.REALIZED));
        assertEquals("call-adapter stub + owned model (generator-policy)",
                report.policies().get("uncharted-realization"));
    }

    // ── E2E: üretilen app gerçek mvn compile (DoD) ──────────────────────────────────────────────

    @org.junit.jupiter.api.Tag("e2e")
    @Test
    void generatedApp_realMvnCompile_exitsZero_afterT44(@TempDir Path outDir) throws IOException, InterruptedException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());
        Path humanPom = outDir.resolve("pom.xml");

        ProcessBuilder pb = new ProcessBuilder("mvn", "-q", "-f", humanPom.toString(), "compile");
        pb.redirectErrorStream(true);
        Process process = pb.start();
        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        int exitCode = process.waitFor();

        assertEquals(0, exitCode, "mvn compile exit 0 bekleniyor; çıktı:\n" + output);
    }
}
