package techgen.spring;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import techgen.core.gm.GenerationModel;
import techgen.core.model.ContractFile;
import techgen.core.model.ManifestJson;
import techgen.core.pipeline.GmBuilder;
import techgen.core.pipeline.Loader;
import techgen.core.report.BuildReport;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * T4.3 — Trigger ({@code @trigger.*} ext → SmartLifecycle stub + seam; SPEC M4; referans
 * {@code docs/referans/gen-dotnet-emisyon-sozlesmesi.md} §1 Trigger (`:1105-1123`) + §2 seam
 * marker'ları). Fixture canlı örnek: WriteAuditLog {@code @trigger.cron} (Ops modülü).
 *
 * <p>Rule 9: {@code realized("@trigger.cron", "WriteAuditLog")} T3.7'nin ext döngüsünde
 * (ExtPartial paritesi, {@code SpringEmitter.extFields}) zaten üretilir; bu task TEKRARLAMAZ —
 * {@link #trigger_realizedEntry_isExactlyOnce_fromT37ExtLoop()} bunu doğrular.</p>
 */
class TriggerEmitTest {

    private static Path fixture(String name) {
        Path fromModuleDir = Path.of("../fixtures", name);
        if (Files.exists(fromModuleDir)) {
            return fromModuleDir;
        }
        return Path.of("fixtures", name);
    }

    private static GenerationModel fixtureGm() {
        Path manifestPath = fixture("manifest.json");
        ManifestJson manifest = Loader.loadManifest(manifestPath);
        ContractFile contract = Loader.loadContract(manifestPath, manifest.contract());
        return GmBuilder.build(manifest, contract);
    }

    private static GenConfig h2Config() {
        return new GenConfig("h2", "inmemory");
    }

    private static String read(Path outDir, String relPath) throws IOException {
        return Files.readString(outDir.resolve(relPath), StandardCharsets.UTF_8);
    }

    private static final String BASE_PATH = "gen/java/app/ops/writeauditlog/WriteAuditLogCronTriggerBase.java";
    private static final String SEAM_PATH = "src/main/java/app/ops/writeauditlog/WriteAuditLogCronTrigger.java";

    // ── TriggerBase (gen-owned, WriteAlways) ──────────────────────────────────────────────────────

    @Test
    void writeAuditLog_triggerBase_isEmitted_withSmartLifecycleStubShape(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, BASE_PATH);
        assertTrue(content.contains("package app.ops.writeauditlog;"));
        assertTrue(content.contains("import org.springframework.context.SmartLifecycle;"));
        assertTrue(content.contains("public abstract class WriteAuditLogCronTriggerBase implements SmartLifecycle {"));
        assertTrue(content.contains("protected final WriteAuditLogHandler handler;"), "ctor'da {Op}Handler alanı eksik");
        assertTrue(content.contains("protected WriteAuditLogCronTriggerBase(WriteAuditLogHandler handler) {"));
        assertTrue(content.contains("public abstract void start();"), "start() soyut bildirim eksik");
        assertTrue(content.contains("public boolean isRunning() {"), "isRunning gen-owned eksik");
        assertTrue(content.contains("public void stop() {"), "stop gen-owned eksik");
        // GEN_HEADER prepend edilir (WriteAlways .java disposition'ı).
        assertTrue(content.startsWith("// <auto-generated/>"));
    }

    // ── Human seam (writeIfAbsent, marker) ────────────────────────────────────────────────────────

    @Test
    void writeAuditLog_triggerSeam_isEmitted_withUnsupportedMarker(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, SEAM_PATH);
        assertTrue(content.contains("package app.ops.writeauditlog;"));
        assertTrue(content.contains("public class WriteAuditLogCronTrigger extends WriteAuditLogCronTriggerBase {"));
        assertTrue(content.contains("public WriteAuditLogCronTrigger(WriteAuditLogHandler handler) {"));
        assertTrue(content.contains("super(handler);"));
        assertTrue(content.contains(
                "throw new UnsupportedOperationException(\"WriteAuditLogCronTrigger.start: doldurulacak\");"));
        // Seam dosyası GEN_HEADER ALMAZ (insan-sahipli, writeIfAbsent).
        assertTrue(!content.startsWith("// <auto-generated/>"));
    }

    @Test
    void writeAuditLog_triggerSeam_secondEmit_doesNotOverwrite(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        Path seamFile = outDir.resolve(SEAM_PATH);
        String custom = "package app.ops.writeauditlog;\n\n"
                + "public class WriteAuditLogCronTrigger extends WriteAuditLogCronTriggerBase {\n"
                + "    public WriteAuditLogCronTrigger(WriteAuditLogHandler handler) { super(handler); }\n"
                + "    @Override public void start() { /* insan tarafından doldurulmuş */ running = true; }\n"
                + "}\n";
        Files.writeString(seamFile, custom, StandardCharsets.UTF_8);

        // ikinci emit: seam EZİLMEMELİ.
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String afterSecondEmit = read(outDir, SEAM_PATH);
        assertEquals(custom, afterSecondEmit, "ikinci emit human seam'i ezmemeli (WriteIfAbsent)");
    }

    @Test
    void writeAuditLog_triggerBase_secondEmit_isRewrittenIfChanged(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());
        String first = read(outDir, BASE_PATH);

        // ikinci emit: gen-owned TriggerBase her run yeniden üretilir (WriteAlways; write-only-if-changed).
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());
        String second = read(outDir, BASE_PATH);

        assertEquals(first, second, "TriggerBase içeriği deterministik olmalı (aynı GM → aynı içerik)");
    }

    // ── Wiring EXPLICIT @Bean (SPEC §12/4 tam-açık kayıt; component-scan YOK) ─────────────────────

    @Test
    void opsWiring_hasExplicitTriggerBean(@TempDir Path outDir) throws IOException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());

        String content = read(outDir, "gen/java/app/ops/OpsWiring.java");
        assertTrue(content.contains("import app.ops.writeauditlog.WriteAuditLogCronTrigger;"));
        assertTrue(content.contains("public WriteAuditLogCronTrigger writeAuditLogCronTrigger(WriteAuditLogHandler h) {"));
        assertTrue(content.contains("return new WriteAuditLogCronTrigger(h);"));
        assertTrue(!content.contains("@ComponentScan"), "component-scan YASAK (SPEC §12/4 tam-açık kayıt)");
    }

    // ── Policy + realized (rule 9: çift-entry YOK) ────────────────────────────────────────────────

    @Test
    void triggerWiringPolicy_isRecorded(@TempDir Path outDir) throws IOException {
        BuildReport report = new BuildReport();
        SpringEmitter.emit(fixtureGm(), outDir, report, h2Config());

        assertTrue(report.policies().containsKey("trigger-wiring"));
        assertEquals("SmartLifecycle stub (generator-policy)", report.policies().get("trigger-wiring"));
    }

    @Test
    void trigger_realizedEntry_isExactlyOnce_fromT37ExtLoop(@TempDir Path outDir) throws IOException {
        BuildReport report = new BuildReport();
        SpringEmitter.emit(fixtureGm(), outDir, report, h2Config());

        long count = report.entries().stream()
                .filter(e -> e.construct().equals("@trigger.cron") && e.id().equals("WriteAuditLog"))
                .count();
        assertEquals(1, count, "@trigger.cron realize TAM 1 kez olmalı (T3.7 ExtPartial paritesi; "
                + "T4.3 kendi realized() çağrısını YAPMAZ — rule 9)");
    }

    // ── Üretilen app gerçek mvn compile (DoD) ─────────────────────────────────────────────────────

    @org.junit.jupiter.api.Tag("e2e")
    @Test
    void generatedApp_realMvnCompile_exitsZero_afterT43(@TempDir Path outDir) throws IOException, InterruptedException {
        SpringEmitter.emit(fixtureGm(), outDir, new BuildReport(), h2Config());
        Path humanPom = outDir.resolve("pom.xml");

        ProcessBuilder pb = new ProcessBuilder("mvn", "-q", "-f", humanPom.toString(), "compile");
        pb.redirectErrorStream(true);
        Process process = pb.start();
        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        int exitCode = process.waitFor();

        assertEquals(0, exitCode, "mvn compile exit 0 bekleniyor; çıktı:\n" + output);
    }
}
