package techgen.spring;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

/**
 * Emit yazım altyapısı (davranış sözleşmesi §3 INV-S seam, §6.1-6.2; referans
 * {@code docs/referans/gen-dotnet-emisyon-sozlesmesi.md} §2/§5/§8; CoreTemplate1
 * {@code DotnetEmitter.cs} karşılığı: {@code WriteAlways}/{@code WriteIfAbsent}/
 * {@code MigrateSeamIfFlat}/{@code WriteProvenanceAndPrune}, satır 656-694 ve 168-199).
 *
 * <p>İki yazım disposition'ı taşır: üreteç-sahibi ağaç için {@link #writeAlways} (her run
 * yeniden yazılır, write-only-if-changed, prune'a tabi) ve insan-sahibi seam için
 * {@link #writeIfAbsent} (yalnız yoksa yazılır, asla ezilmez, prune DIŞI). {@link #finishAndPrune}
 * bu run'da yazılmayan önceki-üretilmiş dosyaları siler ve yeni {@code provenance.json}'ı yazar.</p>
 */
public final class EmitWriter {

    /**
     * Üreteç-sahibi {@code .java} dosyalarının başına eklenen tek satırlık marker. Unicode
     * kaçış dizisi ({@code —} = em dash) kaynak dosya kodlamasından bağımsız birebir
     * karakteri garantiler.
     */
    static final String GEN_HEADER =
            "// <auto-generated/>  — techgen-spring; elle DÜZENLEME: her üretimde ezilir\n";

    private static final String GENERATOR = "techgen-spring";

    private final Path outDir;
    private final List<WrittenFile> written = new ArrayList<>();

    public EmitWriter(Path outDir) {
        this.outDir = outDir;
    }

    /** Bu run'da {@link #writeAlways} ile kaydedilen (relPath, sha256) girdilerinin değişmez görünümü. */
    public List<WrittenFile> written() {
        return List.copyOf(written);
    }

    /**
     * Üreteç-sahibi dosya: içerik her run'da bu olmalıdır. {@code relPath} {@code .java} ile
     * bitiyorsa başına {@link #GEN_HEADER} eklenir. write-only-if-changed: diskteki içerik
     * byte-aynıysa dosyaya DOKUNULMAZ (mtime korunur). Yazılsın ya da yazılmasın, her çağrı
     * provenance/prune için {@code written} listesine (relPath, sha256(finalContent)) eklenir.
     */
    public void writeAlways(String relPath, String content) throws IOException {
        String finalContent = relPath.endsWith(".java") ? GEN_HEADER + content : content;
        String sha = sha256Hex(finalContent);
        written.add(new WrittenFile(relPath, sha));

        Path target = outDir.resolve(relPath);
        if (Files.exists(target)) {
            String existing = Files.readString(target, StandardCharsets.UTF_8);
            if (existing.equals(finalContent)) {
                return;
            }
        }
        Files.createDirectories(target.getParent());
        Files.writeString(target, finalContent, StandardCharsets.UTF_8);
    }

    /**
     * İnsan/LLM-sahibi seam: dosya VARSA hiçbir şey yapılmaz (asla ezilmez); yoksa dizin
     * oluşturulup yazılır. Provenance/prune DIŞI — {@code written} listesine ASLA eklenmez.
     */
    public void writeIfAbsent(String relPath, String content) throws IOException {
        Path target = outDir.resolve(relPath);
        if (Files.exists(target)) {
            return;
        }
        Files.createDirectories(target.getParent());
        Files.writeString(target, content, StandardCharsets.UTF_8);
    }

    /**
     * Brownfield migrasyon: eski düz yerleşimdeki seam dosyası hâlâ duruyorsa ve yeni slice
     * yolunda karşılığı yoksa, gövde KORUNARAK (kopya değil, {@link Files#move}) yeni yola
     * taşınır. Bunun dışında hiçbir şey yapmaz; sonrasında normal {@link #writeIfAbsent} akışı
     * çağıranın sorumluluğudur (emisyon şablonları, T3.2+).
     */
    public void migrateSeamIfFlat(Path oldFlat, Path newSlice) throws IOException {
        if (Files.exists(oldFlat) && !Files.exists(newSlice)) {
            Files.createDirectories(newSlice.getParent());
            Files.move(oldFlat, newSlice);
        }
    }

    /**
     * Orphan prune + provenance yazımı (davranış sözleşmesi §5, {@code WriteProvenanceAndPrune}
     * karşılığı). Sıra:
     * <ol>
     *   <li>Önceki {@code provenance.json}'ı {@link ProvenanceIo#tryRead} ile oku; {@code null}
     *       (yok/bozuk) ise prune ATLANIR (canlı dosya yanlışlıkla silinmesin).</li>
     *   <li>Önceki {@code Generated} path'lerinden bu run'da {@code written}'da OLMAYANLARI sil;
     *       {@code written} dışı hiçbir path'e dokunulmaz (human dosyaları provenance'ta zaten yok).</li>
     *   <li>Silme olduysa artık-boş dizinleri en-derin-önce sil.</li>
     *   <li>Yeni provenance'ı ({@code generator=techgen-spring}, verilen {@code version},
     *       {@code files=written}) yaz — {@link ProvenanceIo#write} ordinal path-sıralar ve
     *       atomik yazar.</li>
     * </ol>
     */
    public void finishAndPrune(String version) throws IOException {
        Provenance previous = ProvenanceIo.tryRead(outDir);

        boolean pruned = false;
        if (previous != null) {
            Set<String> writtenPaths = new HashSet<>();
            for (WrittenFile w : written) {
                writtenPaths.add(w.path());
            }
            for (ProvenanceEntry entry : previous.files()) {
                if (writtenPaths.contains(entry.path())) {
                    continue;
                }
                Path abs = outDir.resolve(entry.path());
                if (Files.exists(abs)) {
                    Files.delete(abs);
                    pruned = true;
                }
            }
        }

        if (pruned) {
            pruneEmptyDirectories();
        }

        List<ProvenanceEntry> entries = written.stream()
                .map(w -> new ProvenanceEntry(w.path(), "Generated", w.sha256()))
                .toList();
        ProvenanceIo.write(outDir, new Provenance(GENERATOR, version, entries));
    }

    /** Artık-boş dizinleri en-derin-önce siler (yalnız orphan dosya silindiğinde çağrılır). */
    private void pruneEmptyDirectories() throws IOException {
        List<Path> dirs;
        try (Stream<Path> walk = Files.walk(outDir)) {
            dirs = walk.filter(p -> !p.equals(outDir))
                    .filter(Files::isDirectory)
                    .sorted(Comparator.comparing(Path::toString).reversed())
                    .toList();
        }
        for (Path dir : dirs) {
            if (Files.exists(dir) && isEmptyDirectory(dir)) {
                Files.delete(dir);
            }
        }
    }

    private static boolean isEmptyDirectory(Path dir) throws IOException {
        try (Stream<Path> entries = Files.list(dir)) {
            return entries.findAny().isEmpty();
        }
    }

    /** UTF-8 içerik string'inden (asla dosyadan geri okuyarak değil) SHA-256 → lowercase hex. */
    private static String sha256Hex(String content) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(content.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder(hash.length * 2);
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 algoritması bulunamadı (JVM garantisi ihlali)", e);
        }
    }

    /** Bu run'da {@link #writeAlways} ile yazılan bir dosyanın provenance-adayı kaydı. */
    public record WrittenFile(String path, String sha256) {
    }
}
